# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk
      - image: circleci/postgres:9.6.5-alpine-ram

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
      DATABASE_URL: jdbc:postgresql://localhost:5432/bumblebee
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres

    steps:
      - checkout

      - run: sudo apt-get update
      - run: sudo apt-get install postgresql-client-9.6
      - run:
          command: |
            psql -h localhost -U postgres -c "CREATE DATABASE bumblebee;"
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run: ./gradlew test